version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      #  mkdir -p $HOME/docker/volumes/postgres
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  mafia-server-go:
    build: .
    ports:
      - "8080:8081"
    depends_on:
      - db
    links:
      - db